apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deploy
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: smarkov05/micro-collector:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8883
---
apiVersion: v1
kind: Service
metadata:
  name: collector-service
spec:
  type: NodePort
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 8883
      targetPort: 8883
      nodePort: 30883