apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipient-deploy
  labels:
    app: recipient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipient
  template:
    metadata:
      labels:
        app: recipient
    spec:
      containers:
        - name: recipient
          image: smarkov05/micro-recipient:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8882
---
apiVersion: v1
kind: Service
metadata:
  name: recipient-service
spec:
  selector:
    app: recipient
  ports:
    - protocol: TCP
      port: 8882
      targetPort: 8882
