apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deploy
  labels:
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: smarkov05/micro-sender:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8881
---
apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  type: NodePort
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
      nodePort: 30881