apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualiser-deploy
  labels:
    app: visualiser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualiser
  template:
    metadata:
      labels:
        app: visualiser
    spec:
      containers:
        - name: visualiser
          image: smarkov05/micro-visualiser:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8884
---
apiVersion: v1
kind: Service
metadata:
  name: visualiser-service
spec:
  type: NodePort
  selector:
    app: visualiser
  ports:
    - protocol: TCP
      port: 8884
      targetPort: 8884
      nodePort: 30884