spring:
  config:
    activate:
      on-profile: docker-env
  application:
    name: api-gateway

server:
  port: 8080

docker:
  discoveryService:
    containerName: eureka-7

eureka:
  instance:
    preferIpAddress: true
  client:
    instance-info-replication-interval-seconds: 10
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${docker.discoveryService.containerName}:8761/eureka}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus