server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}