docker:
  containerNames:
    discoveryService: eureka-7
    rabbitmq: rabbit-7

spring:
  config:
    activate:
      on-profile: docker-env
  application:
    name: sender-service
  rabbitmq:
    host: ${docker.containerNames.rabbitmq}
    port: 5672
    username: user
    password: password

server:
  port: 8881

eureka:
  instance:
    preferIpAddress: true
  client:
    instance-info-replication-interval-seconds: 10
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${docker.containerNames.discoveryService}:8761/eureka}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

